# Generated by Django 5.0.1 on 2024-01-22 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="passsword",
            new_name="password",
        ),
    ]
