# Generated by Django 5.0.1 on 2024-01-23 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_rename_passsword_user_password"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table="users",
        ),
    ]
